#!/bin/bash

# Restores the database from backups generated by mongodump.
# .env should be a file with the MONGODB_USERNAME and MONGODB_PASSWORD in the same directory as this file
# defined as bash variables (a standard .env file should do the trick)

source .env
# CLUSTER_URL="qbreader.0i7oej9"
CLUSTER_URL="qbreader2.z35tynb"
URI="mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${CLUSTER_URL}.mongodb.net/?retryWrites=true&w=majority"

mongorestore -d qbreader --uri=$URI -c tossups dump/qbreader/tossups.bson
mongorestore -d qbreader --uri=$URI -c bonuses dump/qbreader/bonuses.bson
mongorestore -d qbreader --uri=$URI -c packets dump/qbreader/packets.bson
mongorestore -d qbreader --uri=$URI -c sets dump/qbreader/sets.bson

mongorestore -d geoword --uri=$URI -c audio dump/geoword/audio.bson
mongorestore -d geoword --uri=$URI -c buzzes dump/geoword/buzzes.bson
mongorestore -d geoword --uri=$URI -c division-choices dump/geoword/division-choices.bson
mongorestore -d geoword --uri=$URI -c packets dump/geoword/packets.bson
mongorestore -d geoword --uri=$URI -c payments dump/geoword/payments.bson
mongorestore -d geoword --uri=$URI -c sample-audio dump/geoword/sample-audio.bson
mongorestore -d geoword --uri=$URI -c tossups dump/geoword/tossups.bson

mongorestore -d account-info --uri=$URI -c bonus-stars dump/account-info/bonus-stars.bson
mongorestore -d account-info --uri=$URI -c per-bonus-data dump/account-info/per-bonus-data.bson
mongorestore -d account-info --uri=$URI -c per-tossup-data dump/account-info/per-tossup-data.bson
mongorestore -d account-info --uri=$URI -c tossup-stars dump/account-info/tossup-stars.bson
mongorestore -d account-info --uri=$URI -c users dump/account-info/users.bson
